### ISSUE TITLE
SLS Login fails without serverless.yml file

### ISSUE THREAD

**Issue by serverlessguru** [serverless-components/express#1]
Issue:
After running `npm install -g serverless@components`, then running `sls login`, I'm seeing the following error show up.

Error:
```
sls login
 
  Error --------------------------------------------------
 
  Error: The following file could not be found: undefined
      at Object.loadInstanceConfig (/usr/local/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:162:11)
      at Object.runningComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/components/src/legacy.js:8:32)
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:32:25)
      at Module._compile (internal/modules/cjs/loader.js:776:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
      at Module.load (internal/modules/cjs/loader.js:643:32)
      at Function.Module._load (internal/modules/cjs/loader.js:556:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
      at internal/main/run_main_module.js:17:11
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.6.0
     Framework Version:         1.63.0-components-v2-beta
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Version:        undefined
```

I was following the README [here](https://github.com/serverless-components/express#2-login), but it looks like you can't `sls login` before you have a `serverless.yml` file so it could make sense to switch #2 and #3 to create the template first, setup your org/name/app, then `sls login`.
<img width="978" alt="Screen Shot 2020-02-24 at 4 14 17 PM" src="https://user-images.githubusercontent.com/39802277/75202632-ba09dd00-5720-11ea-8055-eee3192a03dc.png">

**Comment by eahefnawy** [comment]
Fixed
