### ISSUE TITLE
SLS Login fails without certain serverless.yml fields

### ISSUE THREAD

**Issue by serverlessguru** [serverless-components/express#2]
Issue:
After running `npm install -g serverless@components`, then creating an empty `serverless.yml` file and running `sls login`, I'm seeing the following error show up.

Error:
```
➜  slspro git:(master) ✗ touch serverless.yml
➜  slspro git:(master) ✗ sls login                           
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'name' of undefined
      at Object.loadInstanceConfig (/usr/local/lib/node_modules/serverless/node_modules/@serverless/components/src/cli/utils.js:181:21)
      at Object.runningComponents (/usr/local/lib/node_modules/serverless/node_modules/@serverless/components/src/legacy.js:8:32)
      at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless.js:32:25)
      at Module._compile (internal/modules/cjs/loader.js:776:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
      at Module.load (internal/modules/cjs/loader.js:643:32)
      at Function.Module._load (internal/modules/cjs/loader.js:556:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
      at internal/main/run_main_module.js:17:11
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.6.0
     Framework Version:         1.63.0-components-v2-beta
     Plugin Version:            3.4.1
     SDK Version:               2.3.0
     Components Version:        undefined
```

I was following the README [here](https://github.com/serverless-components/express#2-login), but it looks like you can't `sls login` before you have certain fields in your `serverless.yml` file so it could make sense to switch #2 and #3 to create the template first, then explain what fields need to be setup in order to run `sls login`.

Related issue: https://github.com/serverless-components/express/issues/1

**Comment by eahefnawy** [comment]
Fixed
